### ISSUE TITLE
HTF's test suite does not work with `stack`

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#106]
In preparation for a LTS submission, I ran
```
stack build --haddock --test --bench --no-run-benchmarks --stack-yaml stack-lts-8.10.yaml
```
(where stack-lts-... is like stack-ghc-... only with resolver lts and extra-dep haskell-src).

Most tests fail, it looks like the first failing one is:
```
[TEST] unitTest
HUnitFailure (Just (SrcLoc {srcLocPackage = "HTF-0.14.0.6-LAG5rAlfqCRFLfwk8DIfrz", srcLocModule = "Test.Framework.TestManager", srcLocFile = "./Test/Framework/TestManager.hs", srcLocStartLine = 508, srcLocStartCol = 22, srcLocEndLine = 508, srcLocEndCol = 45})) (Reason "Fail")
@@@ Error! (0ms)

* Tests:     1
* Passed:    0
* Pending:   0
* Failures:  0
* Errors:    1
* Timed out: 0
* Filtered:  0

* Errors:
  * unitTest

Total execution time: 0ms
Cases: 6  Tried: 6  Errors: 0  Failures: 0
``` 

Could it be that some paths are hardwired in the testsuite that shouldn't be?

**Comment by skogsbaer** [comment]
The tests are a bit involved, indeed. That's mainly because there are also some integration tests that depend on the htfpp program.

The problem is that you need to set the environment variable `HTF_TEST_STACK_ARGS` to something like `HTF_TEST_STACK_ARGS='--stack-yaml stack-ghc-8.10.yaml'` if you want to use a custom stack.yml file.

Please use the branch `fix-tests`, it adds debugging support and introduces `HTF_TEST_STACK_ARGS` (it was named differently before). See https://github.com/skogsbaer/HTF/pull/107
